# Generated by Django 3.0.1 on 2019-12-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.HorarioAgenda'),
        ),
    ]
