# Generated by Django 3.0.1 on 2019-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='num_verificacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
