# Generated by Django 3.0.1 on 2019-12-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissional', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profi_ativo', models.BooleanField(default=True)),
                ('id_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.Clinica')),
                ('id_profi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profissional.Profissional')),
            ],
        ),
    ]
